"""empty message

Revision ID: 19c009eb801
Revises: d4773d8d1
Create Date: 2015-03-22 08:07:37.968321

"""

# revision identifiers, used by Alembic.
revision = '19c009eb801'
down_revision = 'd4773d8d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
